### ISSUE TITLE
Game Crashes before fully loading.

### ISSUE THREAD

**Issue by CocoaTheBoo** [Chefs-Delight/Farmersrespite-Fabric#19]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/20/23, 5:40 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'farmersrespite'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraftforge.api.ModLoadingContext.registerConfig(java.lang.String, net.minecraftforge.fml.config.ModConfig$Type, net.minecraftforge.fml.config.IConfigSpec)'
	at com.chefsdelights.farmersrespite.core.FarmersRespite.onInitialize(FarmersRespite.java:52)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.2673 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.23050.5 (b79513656627928b5505482e6c59e640a77adba5):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.3031 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.2486 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll
		java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft
		jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jna4289874312340865516.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ntdll.dll:NT Layer DLL:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		win32u.dll:Win32u:10.0.19041.3086 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3816276992 bytes (3639 MiB) / 5024776192 bytes (4792 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 21452.25
	Virtual memory used (MB): 15110.60
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 408.83
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Fabric Mods: 
		architectury: Architectury 4.11.93
		armor_hud: BerdinskiyBear's ArmorHUD 0.3.6
		artifacts: Artifacts 7.0.3+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		bclib: BCLib 1.4.7
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.3.1
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.1
		betterfortresses: YUNG's Better Nether Fortresses 1.18.2-Fabric-1.0.0
			org_reflections_reflections: reflections 0.10.2
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betternether: Better Nether 6.1.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.18.2-Fabric-1.0.3
		bettersleeping: BetterSleeping 0.6.1+1.17
			bettersleeping-core: BetterSleeping Core 0.6.1
			org_apache_commons_commons-text: commons-text 1.9
		bettervillage: Better village 3.0.0
		betterwitchhuts: YUNG's Better Witch Huts 1.18.2-Fabric-1.0.1
		bobby: Bobby 3.1.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		brewinandchewin: Brewin And Chewin fabric-2.0.2+1.18.2
			booking_it: Booking It unversioned
			mm: Manningham Mills 2.3
		celib: Celib 1.1.0+1.18.2
		chefsdelight: Chef's Delight 1.0.3-fabric-1.18.2
			structurized-reborn: Structurized Reborn 1.18.2-01
		chipped: Chipped 2.0.1
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		comforts: Comforts 1.1.3-1.18.2
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		continuity: Continuity 2.0.2+1.18.2
		crittersandcompanions: Critters and Companions 1.18.2-1.0.2
		ctm: ConnectedTexturesMod for Fabric 1.0.0+1.18
		culturaldelights: Cultural Delights Fabric 0.14.7+1.18.2
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18.2
		eldritch_mobs: EldritchMobs 1.11.7
		emerald_tools: Emerald Tools 1.3.48
			pugh_tools: Pugh Tools 1.2.7
		expandeddelight: Expanded Delight 0.1.9.2
		extraorigins: Extra Origins 1.18-12
		extrasounds: ExtraSounds 2.3.1+1.18.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
			soundcategories: Sound Categories 1.2.4+1.18
		fabric-api: Fabric API 0.76.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.5.0+bf48649860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.1+03e2b68760
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.12+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.14+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.8+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricenchantments: Fabric Enchantments 0.7.2
		fabricloader: Fabric Loader 0.14.21
		farmersdelight: Farmer's Delight 1.18.2-1.2.5
		farmersknives: Farmer's Knives 1.3.1
		farmersrespite: Farmer's Respite 1.0.0
			porting_lib: Porting Lib 1.2.614-beta+1.18.2-stable
				forge_tags: Forge Tags 2.1
				serialization_hooks: Serialization Hooks 0.3.23
		forgeconfigapiport: Forge Config API Port 3.2.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		friendsandfoes: Friends&Foes 1.4.7
		geckolib3: Geckolib 3.0.80
			com_eliotlash_mclib_mclib: mclib 20
		harvest_scythes: Harvest Scythes 2.5.3+mc1.18.2
		hidearmor: Hide Armor 2.5
		indium: Indium 1.0.7+mc1.18.2
		java: OpenJDK 64-Bit Server VM 17
		kiwi: Kiwi Lib 6.0.2
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		libraryferret: Library ferret 4.0.0
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.5
		morediscs: More discs 1.18.2-28-fabric
		morevillagers: More Villagers 3.3.2
		mythicmounts: Mythic Mounts 1.18.2-7.1
		nethersdelight: Nether's Delight 2.0.0
			disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		oceansdelight: Ocean's Delight 1.0.0
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
				playerabilitylib: Pal 1.5.0
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		patchouli: Patchouli 1.18.2-66-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.5+1.14.4-1.20
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		pfm: Paladin's Furniture 1.1.1
		presencefootsteps: Presence Footsteps 1.5.1
			kirin: Kirin UI 1.10.0
		recipe-book-delight: Recipe Book Delight 0.1.0-1.18.2
			cracker-util-base: CrackerUtil Base 0.4.1-1.18.2
				com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
			cracker-util-enums: CrackerUtil Enums 0.4.1-1.18.2
			cracker-util-recipe-book: CrackerUtil Recipe Book 0.4.1-1.18.2
		refabslab: Refabricated Slabs 0.7.4
			cardinal-components-base: Cardinal Components API (base) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
		respro: Resource Provider Library 0.2.2+1.18.2
		roughlyenoughitems: Roughly Enough Items 8.3.618
			error_notifier: Error Notifier 1.0.9
		seasons: Fabric Seasons 1.4-BETA+1.18
		simple_shelves: Simple Shelves 1.0.7
		snowrealmagic: Snow! Real Magic! 4.1.3
		snowundertrees: Snow Under Trees 1.0.0+1.18.2
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.9-a
		trinkets: Trinkets 3.3.1
		voicechat: Simple Voice Chat 1.18.2-2.4.9
		wearablebackpacks: Example Mod 1.0.1
		xaerominimap: Xaero's Minimap 23.4.4
		yungsapi: YUNG's API 1.18.2-Fabric-2.2.9
			org_javassist_javassist: javassist 3.28.0-GA
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
	Launched Version: fabric-loader-0.14.21-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by AmadDev24** [comment]
Idk if we have a same problem but I also have those crash problems until I run together with [Deprecated version](https://modrinth.com/mod/farmers-delight-fabric), its worked but now we have new problem with kettle #35
