### ISSUE TITLE
Failed to start the minecraft server (farmers-delight-fabric-1.19.2-1.3.10 Update)

### ISSUE THREAD

**Issue by whatamaniac** [Chefs-Delight/Farmersrespite-Fabric#21]
Hello,
         Mod fails to load on server with the latest Farmers Delight Update. Here's my log file:
[latest.log](https://github.com/Chefs-Delight/Farmersrespite-Fabric/files/12002408/latest.log)
Lemme know if you need anything else ^_^

**Comment by noncom** [comment]
Confirming. Tried updating -- getting the same exception. Had to roll back Farmers Delight for now.

**Comment by Shibva** [comment]
can confirm as well

appears to have been caused by the slight change made to inventory


```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-07-13 12:51:43
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'farmersrespite'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/nhoryzon/mc/farmersdelight/entity/block/inventory/ItemHandler
	at com.chefsdelights.farmersrespite.core.registry.FRBlockEntityTypes.<clinit>(FRBlockEntityTypes.java:10)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.google.common.reflect.Reflection.initialize(Reflection.java:66)
	at com.chefsdelights.farmersrespite.core.FarmersRespite.onInitialize(FarmersRespite.java:37)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.nhoryzon.mc.farmersdelight.entity.block.inventory.ItemHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
```
