### ISSUE TITLE
Kettle doesn't work on Refabricated port with QFAPI

### ISSUE THREAD

**Issue by Adlumia7** [Chefs-Delight/Farmersrespite-Fabric#33]
Interacting with the Kettle to open its UI in the current built of the Refabricated port using Quilt results in this error, and the Kettle not opening:
[23:44:44] [Server thread/ERROR]:
 Failed to handle packet net.minecraft.class_2885@30e0589, suppressing error
java.lang.IllegalArgumentException: [Fabric] Extended screen handler farmersrespite:kettle must be opened with an ExtendedScreenHandlerFactory!
    at net.minecraft.class_3222.handler$eno000$quilted_fabric_screen_handler_api_v1$fabric_storeOpenedScreenHandler(class_3222.java:7939) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_3222.method_17355(class_3222.java:1041) ~[minecraft-1.20.1.i0:0/:?]
    at com.chefsdelights.farmersrespite.common.block.KettleBlock.method_9534(KettleBlock.java:119) ~[farmersrespite-3.0.2.i0:0/:?]
    at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_3738.run(class_3738.java:18) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[minecraft-1.20.1.i0:0/:?]
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-1.20.1.i0:0/:?]
    at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by csthenry** [comment]
The kettle page cannot be opened when there is an item in hand.
```
[Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@3ebf56fb, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$0" is null
        at net.minecraft.class_1799.<init>(class_1799.java:169) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.<init>(class_1799.java:152) ~[server-intermediary.jar:?]
        at com.chefsdelights.farmersrespite.common.block.entity.KettleBlockEntity.isContainerValid(KettleBlockEntity.java:454) ~[Farmersrespite-Fabric-3.0.5.jar:?]
        at com.chefsdelights.farmersrespite.common.block.entity.KettleBlockEntity.useHeldItemOnMeal(KettleBlockEntity.java:438) ~[Farmersrespite-Fabric-3.0.5.jar:?]
        at com.chefsdelights.farmersrespite.common.block.KettleBlock.method_9534(KettleBlock.java:110) ~[Farmersrespite-Fabric-3.0.5.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
