### ISSUE TITLE
Can't right click the kettle at all.

### ISSUE THREAD

**Issue by fahdicool5** [Chefs-Delight/Farmersrespite-Fabric#35]
I don't know if this is an intended feature at all or if I'm doing something wrong, but whenever I click the kettle, even with an open hand, it simply just doesn't work. I'm using quite a large mod set, and I can provide a list if needed. But if this is an intended feature at all, please let me know. I really appreciate the work you put in porting this, and I hope I can be able to use your mod.

Thanks,

Fahdi

**Comment by MAntis127** [comment]
same issue here I've be unable to fully migrate my personal mod pack because farmers respite dose not wok in 1.20.1 either in a modpack or on its own. kettle ui dsoe not open and thus i cant make tea(mod version 3.0.2)

**Comment by tagrimo** [comment]
I'm having the same issue. I tested with only the following mods and the problem still happens:

fabric-api 0.92.2+1.20.1
farmersdelight 1.20.1-2.1.6+refabricated
farmersrespite 3.0.2
sodium 0.5.11+mc1.20.1

my console output gives me the following error when I right click a kettle:

Failed to handle packet net.minecraft.class_2885@66e3fd4f, suppressing error
java.lang.IllegalArgumentException: [Fabric] Extended screen handler farmersrespite:kettle must be opened with an ExtendedScreenHandlerFactory!
	at knot//net.minecraft.class_3222.handler$bbh000$fabric-screen-handler-api-v1$fabric_storeOpenedScreenHandler(class_3222.java:4898)
	at knot//net.minecraft.class_3222.method_17355(class_3222.java:1041)
	at knot//com.chefsdelights.farmersrespite.common.block.KettleBlock.method_9534(KettleBlock.java:119)
	at knot//net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at knot//net.minecraft.class_3225.method_14262(class_3225.java:343)
	at knot//net.minecraft.class_3244.method_12046(class_3244.java:1140)
	at knot//net.minecraft.class_2885.method_12547(class_2885.java:34)
	at knot//net.minecraft.class_2885.method_11054(class_2885.java:8)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:22)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:156)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:130)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at knot//net.minecraft.class_1255.method_18857(class_1255.java:139)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by DailyEffortBird** [comment]
Is a fix for this planned in the near future?

**Comment by tagrimo** [comment]
Y'all I found an unofficial patch that fixes this issue
https://github.com/Adlumia7/Farmersrespite-Fabric/releases/tag/v3.0.8
